import ShieldIcon from '../components/ShieldIcon';

export default function Privacy() {
  return (
    <div className="legal-page">
      <h1 className="section-title"><ShieldIcon size={22} /> Privacy Policy</h1>
      <p className="legal-updated">Last updated: February 2026</p>

      <div className="legal-body">
        <p>
          covers.cafe ("we", "us", "our") is committed to protecting your personal information.
          This Privacy Policy explains what data we collect, how we use it, and the rights you have
          over your information. By using covers.cafe you agree to the practices described here.
        </p>

        <h2>1. Information We Collect</h2>
        <p>We collect information you provide directly and information generated by your use of the service:</p>
        <ul>
          <li><strong>Account data:</strong> email address, username, display name, bio, and profile picture when you register.</li>
          <li><strong>Content you upload:</strong> album cover images and associated metadata (title, artist, year, tags).</li>
          <li><strong>Activity data:</strong> covers you favorite, covers you download, covers you report.</li>
          <li><strong>Technical data:</strong> IP address, browser type, operating system, referrer URL, and pages visited, collected automatically via server logs and our hosting provider.</li>
        </ul>
        <p>We do <strong>not</strong> collect payment information, run advertising trackers, or sell your data to third parties.</p>

        <h2>2. How We Use Your Information</h2>
        <ul>
          <li>To provide and improve the covers.cafe service.</li>
          <li>To authenticate your account and protect against unauthorized access.</li>
          <li>To display your public profile and uploaded covers to other users.</li>
          <li>To enforce our Terms of Service and respond to abuse reports.</li>
          <li>To send you transactional emails (password resets, account confirmations). We do not send marketing emails.</li>
          <li>To detect and prevent duplicate content, spam, and copyright violations.</li>
        </ul>

        <h2>3. Data Sharing</h2>
        <p>
          We share your data only with the infrastructure providers necessary to operate the service —
          specifically <strong>Supabase</strong> (database and storage) and our hosting provider.
          These providers are bound by their own privacy policies and data processing agreements.
          We do not sell, rent, or trade your personal information with any other third party.
        </p>

        <h2>4. Public Information</h2>
        <p>
          Your username, display name, profile picture, bio, and any cover art you mark as public are
          visible to all visitors of covers.cafe, including non-registered users. Do not include
          personally sensitive information in fields intended to be public.
        </p>

        <h2>5. Data Retention</h2>
        <p>
          We retain your account data and uploaded content for as long as your account is active.
          If you delete your account, your personal data and uploaded covers will be permanently deleted
          within 30 days, except where we are required to retain it for legal or safety reasons.
          Aggregated, anonymized analytics data may be retained indefinitely.
        </p>

        <h2>6. Security</h2>
        <p>
          We implement industry-standard security measures including encrypted connections (HTTPS),
          row-level security policies in our database, and access controls. However, no system is
          completely secure. You are responsible for keeping your password confidential and for any
          activity that occurs under your account.
        </p>

        <h2>7. Cookies and Local Storage</h2>
        <p>
          covers.cafe uses browser local storage to remember your theme preference (light or dark mode)
          and your authentication session. We do not use advertising cookies or cross-site tracking.
        </p>

        <h2>8. Children's Privacy</h2>
        <p>
          covers.cafe is not directed at children under the age of 13. We do not knowingly collect
          personal information from children under 13. If you believe a child has provided us with
          personal information, please contact us and we will delete it promptly.
        </p>

        <h2>9. Your Rights</h2>
        <p>Depending on your jurisdiction, you may have the right to:</p>
        <ul>
          <li>Access the personal data we hold about you.</li>
          <li>Correct inaccurate data.</li>
          <li>Request deletion of your data ("right to be forgotten").</li>
          <li>Object to or restrict our processing of your data.</li>
          <li>Data portability.</li>
        </ul>
        <p>
          To exercise any of these rights, email us at <strong>mstrjk@mstrjk.com</strong>.
          We will respond within 30 days.
        </p>

        <h2>10. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. When we do, we will update the "Last updated"
          date at the top of this page. Continued use of covers.cafe after changes constitutes your
          acceptance of the revised policy. If changes are material, we will make reasonable efforts to
          notify registered users via email.
        </p>

        <h2>11. Contact</h2>
        <p>
          Questions about this policy? Email us at <strong>mstrjk@mstrjk.com</strong>.
        </p>
      </div>

      <style>{`
        .legal-page { max-width: 720px; }
        .legal-updated { font-size: 15px; color: var(--body-text-muted); margin-bottom: 24px; }
        .legal-body { display: flex; flex-direction: column; gap: 0; }
        .legal-body p, .legal-body ul { font-size: 17px; color: var(--body-text); line-height: 1.75; margin: 0 0 14px; }
        .legal-body ul { padding-left: 20px; }
        .legal-body li { margin-bottom: 6px; }
        .legal-body h2 {
          font-size: 16px; font-weight: bold; color: var(--body-text);
          margin: 24px 0 10px;
          padding-bottom: 6px; border-bottom: 1px solid var(--body-card-border);
          text-shadow: 0 1px 0 rgba(255,255,255,0.4);
        }
        [data-theme="dark"] .legal-body h2 { text-shadow: none; }
        .legal-body strong { color: var(--body-text); }
      `}</style>
    </div>
  );
}
