interface Props {
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

// FavoritesIcon — pixel-art icon, fill inherits currentColor for theme support.
// Original viewBox: 120×120.
export default function FavoritesIcon({ size = 18, className, style }: Props) {
  const w = Math.round(size * (120 / 120));
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={w}
      height={size}
      viewBox="0 0 120 120"
      shapeRendering="crispEdges"
      aria-hidden="true"
      className={className}
      style={{ display: 'inline-block', verticalAlign: 'middle', flexShrink: 0, ...style }}
    >
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="26"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="27"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="28"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="29"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="30"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="31"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="57"
        y="32"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="33"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="34"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="35"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="36"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="37"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="38"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="39"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="53"
        y="40"
      />
      <rect
        width="23"
        height="1"
        fill="currentColor"
        x="49"
        y="41"
      />
      <rect
        width="23"
        height="1"
        fill="currentColor"
        x="49"
        y="42"
      />
      <rect
        width="23"
        height="1"
        fill="currentColor"
        x="49"
        y="43"
      />
      <rect
        width="23"
        height="1"
        fill="currentColor"
        x="49"
        y="44"
      />
      <rect
        width="68"
        height="1"
        fill="currentColor"
        x="27"
        y="45"
      />
      <rect
        width="68"
        height="1"
        fill="currentColor"
        x="27"
        y="46"
      />
      <rect
        width="68"
        height="1"
        fill="currentColor"
        x="27"
        y="47"
      />
      <rect
        width="68"
        height="1"
        fill="currentColor"
        x="27"
        y="48"
      />
      <rect
        width="53"
        height="1"
        fill="currentColor"
        x="34"
        y="49"
      />
      <rect
        width="53"
        height="1"
        fill="currentColor"
        x="34"
        y="50"
      />
      <rect
        width="53"
        height="1"
        fill="currentColor"
        x="34"
        y="51"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="38"
        y="52"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="38"
        y="53"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="38"
        y="54"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="38"
        y="55"
      />
      <rect
        width="37"
        height="3"
        fill="currentColor"
        x="42"
        y="55"
      />
      <rect
        width="37"
        height="1"
        fill="currentColor"
        x="42"
        y="57"
      />
      <rect
        width="37"
        height="1"
        fill="currentColor"
        x="42"
        y="58"
      />
      <rect
        width="37"
        height="1"
        fill="currentColor"
        x="42"
        y="59"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="60"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="61"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="62"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="63"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="64"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="65"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="66"
      />
      <rect
        width="30"
        height="1"
        fill="currentColor"
        x="46"
        y="67"
      />
      <rect
        width="37"
        height="1"
        fill="currentColor"
        x="42"
        y="68"
      />
      <rect
        width="37"
        height="1"
        fill="currentColor"
        x="42"
        y="69"
      />
      <rect
        width="37"
        height="1"
        fill="currentColor"
        x="42"
        y="70"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="42"
        y="71"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="64"
        y="71"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="42"
        y="72"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="64"
        y="72"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="42"
        y="73"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="64"
        y="73"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="42"
        y="74"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="64"
        y="74"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="42"
        y="75"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="68"
        y="75"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="42"
        y="76"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="68"
        y="76"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="42"
        y="77"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="68"
        y="77"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="42"
        y="78"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="68"
        y="78"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="38"
        y="79"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="76"
        y="79"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="38"
        y="80"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="76"
        y="80"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="38"
        y="81"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="76"
        y="81"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="38"
        y="82"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="76"
        y="82"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="38"
        y="83"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="80"
        y="83"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="38"
        y="84"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="80"
        y="84"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="38"
        y="85"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="80"
        y="85"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="38"
        y="86"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="80"
        y="86"
      />
    </svg>
  );
}
