interface Props {
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

// TrophyIcon — pixel-art icon, fill inherits currentColor for theme support.
// Original viewBox: 120×120.
export default function TrophyIcon({ size = 18, className, style }: Props) {
  const w = Math.round(size * (120 / 120));
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={w}
      height={size}
      viewBox="0 0 120 120"
      shapeRendering="crispEdges"
      aria-hidden="true"
      className={className}
      style={{ display: 'inline-block', verticalAlign: 'middle', flexShrink: 0, ...style }}
    >
      <rect
        width="59"
        height="4"
        fill="currentColor"
        x="30"
        y="19"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="22"
        y="30"
      />
      <rect
        width="5"
        height="1"
        fill="currentColor"
        x="45"
        y="30"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="58"
        y="30"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="71"
        y="30"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="22"
        y="31"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="45"
        y="31"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="58"
        y="31"
      />
      <rect
        width="12"
        height="3"
        fill="currentColor"
        x="86"
        y="30"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="22"
        y="32"
      />
      <rect
        width="5"
        height="3"
        fill="currentColor"
        x="45"
        y="31"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="58"
        y="32"
      />
      <rect
        width="5"
        height="4"
        fill="currentColor"
        x="70"
        y="30"
      />
      <rect
        width="3"
        height="31"
        fill="currentColor"
        x="30"
        y="21"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="56"
        y="33"
      />
      <rect
        width="4"
        height="3"
        fill="currentColor"
        x="18"
        y="33"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="34"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="56"
        y="34"
      />
      <rect
        width="3"
        height="3"
        fill="currentColor"
        x="98"
        y="33"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="35"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="35"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="56"
        y="35"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="35"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="36"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="36"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="56"
        y="36"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="36"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="37"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="37"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="37"
      />
      <rect
        width="4"
        height="7"
        fill="currentColor"
        x="75"
        y="34"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="37"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="38"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="38"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="38"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="38"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="39"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="39"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="39"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="39"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="40"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="40"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="40"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="40"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="41"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="41"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="41"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="42"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="42"
      />
      <rect
        width="4"
        height="4"
        fill="currentColor"
        x="79"
        y="41"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="42"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="43"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="43"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="43"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="44"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="44"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="44"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="45"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="45"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="45"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="45"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="46"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="46"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="46"
      />
      <rect
        width="4"
        height="5"
        fill="currentColor"
        x="75"
        y="45"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="46"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="18"
        y="47"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="47"
      />
      <rect
        width="15"
        height="1"
        fill="currentColor"
        x="52"
        y="47"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="98"
        y="47"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="48"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="48"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="48"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="37"
        y="49"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="49"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="49"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="71"
        y="49"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="37"
        y="50"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="50"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="50"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="71"
        y="50"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="37"
        y="51"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="51"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="51"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="71"
        y="51"
      />
      <rect
        width="4"
        height="8"
        fill="currentColor"
        x="22"
        y="48"
      />
      <rect
        width="4"
        height="10"
        fill="currentColor"
        x="33"
        y="52"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="48"
        y="52"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="67"
        y="52"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="48"
        y="53"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="67"
        y="53"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="48"
        y="54"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="67"
        y="54"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="48"
        y="55"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="67"
        y="55"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="26"
        y="56"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="56"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="56"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="63"
        y="56"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="90"
        y="56"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="26"
        y="57"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="57"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="57"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="63"
        y="57"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="90"
        y="57"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="26"
        y="58"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="58"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="58"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="63"
        y="58"
      />
      <rect
        width="8"
        height="4"
        fill="currentColor"
        x="71"
        y="56"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="90"
        y="58"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="26"
        y="59"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="59"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="59"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="63"
        y="59"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="83"
        y="59"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="90"
        y="59"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="30"
        y="60"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="48"
        y="60"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="63"
        y="60"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="79"
        y="60"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="30"
        y="61"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="48"
        y="61"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="63"
        y="61"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="79"
        y="61"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="30"
        y="62"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="48"
        y="62"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="63"
        y="62"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="79"
        y="62"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="30"
        y="63"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="48"
        y="63"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="63"
        y="63"
      />
      <rect
        width="11"
        height="1"
        fill="currentColor"
        x="79"
        y="63"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="37"
        y="64"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="75"
        y="64"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="37"
        y="65"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="75"
        y="65"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="37"
        y="66"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="75"
        y="66"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="41"
        y="67"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="75"
        y="67"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="68"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="71"
        y="68"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="69"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="71"
        y="69"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="41"
        y="70"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="71"
        y="70"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="45"
        y="71"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="71"
        y="71"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="45"
        y="72"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="67"
        y="72"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="45"
        y="73"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="67"
        y="73"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="45"
        y="74"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="67"
        y="74"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="75"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="76"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="77"
      />
      <rect
        width="22"
        height="1"
        fill="currentColor"
        x="49"
        y="78"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="79"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="79"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="80"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="80"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="81"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="81"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="82"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="82"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="83"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="83"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="84"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="84"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="85"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="85"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="52"
        y="86"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="64"
        y="86"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="49"
        y="87"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="64"
        y="87"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="49"
        y="88"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="64"
        y="88"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="49"
        y="89"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="64"
        y="89"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="49"
        y="90"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="67"
        y="90"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="45"
        y="91"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="67"
        y="91"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="45"
        y="92"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="67"
        y="92"
      />
      <rect
        width="7"
        height="1"
        fill="currentColor"
        x="45"
        y="93"
      />
      <rect
        width="8"
        height="1"
        fill="currentColor"
        x="67"
        y="93"
      />
      <rect
        width="38"
        height="1"
        fill="currentColor"
        x="41"
        y="94"
      />
      <rect
        width="38"
        height="1"
        fill="currentColor"
        x="41"
        y="95"
      />
      <rect
        width="38"
        height="1"
        fill="currentColor"
        x="41"
        y="96"
      />
      <rect
        width="38"
        height="1"
        fill="currentColor"
        x="41"
        y="97"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="41"
        y="98"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="76"
        y="98"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="41"
        y="99"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="76"
        y="99"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="41"
        y="100"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="76"
        y="100"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="41"
        y="101"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="76"
        y="101"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="37"
        y="102"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="79"
        y="102"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="37"
        y="103"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="79"
        y="103"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="37"
        y="104"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="79"
        y="104"
      />
      <rect
        width="4"
        height="1"
        fill="currentColor"
        x="37"
        y="105"
      />
      <rect
        width="3"
        height="1"
        fill="currentColor"
        x="79"
        y="105"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="37"
        y="106"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="37"
        y="107"
      />
      <rect
        width="45"
        height="1"
        fill="currentColor"
        x="37"
        y="108"
      />
      <rect
        width="4"
        height="10"
        fill="currentColor"
        x="82"
        y="52"
      />
      <rect
        width="4"
        height="8"
        fill="currentColor"
        x="94"
        y="48"
      />
      <rect
        width="3"
        height="31"
        fill="currentColor"
        x="86"
        y="21"
      />
      <rect
        width="4"
        height="4"
        fill="currentColor"
        x="37"
        y="41"
      />
    </svg>
  );
}
