interface Props {
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}

// UploadDownloadIcon — pixel-art icon, fill inherits currentColor for theme support.
// Original viewBox: 120×118.
export default function UploadDownloadIcon({ size = 18, className, style }: Props) {
  const w = Math.round(size * (120 / 118));
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={w}
      height={size}
      viewBox="0 0 120 118"
      shapeRendering="crispEdges"
      aria-hidden="true"
      className={className}
      style={{ display: 'inline-block', verticalAlign: 'middle', flexShrink: 0, ...style }}
    >
      <rect
        x="56"
        y="14"
        width="7"
        height="1"
        fill="currentColor"
      />
      <rect
        x="56"
        y="15"
        width="7"
        height="1"
        fill="currentColor"
      />
      <rect
        x="56"
        y="16"
        width="7"
        height="1"
        fill="currentColor"
      />
      <rect
        x="56"
        y="17"
        width="7"
        height="1"
        fill="currentColor"
      />
      <rect
        x="52"
        y="18"
        width="15"
        height="1"
        fill="currentColor"
      />
      <rect
        x="52"
        y="19"
        width="15"
        height="1"
        fill="currentColor"
      />
      <rect
        x="52"
        y="20"
        width="15"
        height="1"
        fill="currentColor"
      />
      <rect
        x="52"
        y="21"
        width="15"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="22"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="23"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="24"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="45"
        y="25"
        width="30"
        height="1"
        fill="currentColor"
      />
      <rect
        x="45"
        y="26"
        width="30"
        height="1"
        fill="currentColor"
      />
      <rect
        x="45"
        y="27"
        width="30"
        height="1"
        fill="currentColor"
      />
      <rect
        x="45"
        y="28"
        width="30"
        height="1"
        fill="currentColor"
      />
      <rect
        x="41"
        y="29"
        width="37"
        height="1"
        fill="currentColor"
      />
      <rect
        x="41"
        y="30"
        width="37"
        height="1"
        fill="currentColor"
      />
      <rect
        x="41"
        y="31"
        width="37"
        height="1"
        fill="currentColor"
      />
      <rect
        x="41"
        y="32"
        width="37"
        height="1"
        fill="currentColor"
      />
      <rect
        x="37"
        y="33"
        width="45"
        height="1"
        fill="currentColor"
      />
      <rect
        x="37"
        y="34"
        width="45"
        height="1"
        fill="currentColor"
      />
      <rect
        x="37"
        y="35"
        width="45"
        height="1"
        fill="currentColor"
      />
      <rect
        x="34"
        y="36"
        width="50"
        height="1"
        fill="currentColor"
      />
      <rect
        x="84"
        y="36"
        width="2"
        height="1"
        fill="currentColor"
      />
      <rect
        x="34"
        y="37"
        width="52"
        height="1"
        fill="currentColor"
      />
      <rect
        x="34"
        y="38"
        width="52"
        height="1"
        fill="currentColor"
      />
      <rect
        x="34"
        y="39"
        width="52"
        height="1"
        fill="currentColor"
      />
      <rect
        x="30"
        y="40"
        width="59"
        height="1"
        fill="currentColor"
      />
      <rect
        x="30"
        y="41"
        width="59"
        height="1"
        fill="currentColor"
      />
      <rect
        x="30"
        y="42"
        width="59"
        height="1"
        fill="currentColor"
      />
      <rect
        x="30"
        y="43"
        width="59"
        height="1"
        fill="currentColor"
      />
      <rect
        x="26"
        y="44"
        width="67"
        height="1"
        fill="currentColor"
      />
      <rect
        x="26"
        y="45"
        width="67"
        height="1"
        fill="currentColor"
      />
      <rect
        x="26"
        y="46"
        width="67"
        height="1"
        fill="currentColor"
      />
      <rect
        x="26"
        y="47"
        width="64"
        height="1"
        fill="currentColor"
      />
      <rect
        x="90"
        y="47"
        width="3"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="48"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="49"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="50"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="51"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="52"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="53"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="54"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="55"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="56"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="57"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="58"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="59"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="60"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="61"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="62"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="63"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="64"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="65"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="66"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="67"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="68"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="69"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="70"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="71"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="72"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="73"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="74"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="75"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="76"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="77"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="78"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="79"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="80"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="81"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="82"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="83"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="84"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="85"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="86"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="87"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="88"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="89"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="90"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="91"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="92"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="93"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="94"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="95"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="96"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="97"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="98"
        width="22"
        height="1"
        fill="currentColor"
      />
      <rect
        x="49"
        y="99"
        width="22"
        height="1"
        fill="currentColor"
      />
    </svg>
  );
}
